# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [vice, golo]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username Tornado.io
ko_fi: # Replace with a single Ko-fi username yoshi
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/audible
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username Smithla
issuehunt: # Replace with a single IssueHunt username sans.org
otechie: # Replace with a single Otechie username icann
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://ironhorse.com','https://chime.com','https://crest.com', 'https://ring.com']
